### ISSUE TITLE
Errors in running storm test - netCDF4 version issue?

### ISSUE THREAD

**Issue by rjleveque** [clawpack/geoclaw#381]
Trying to run the tests on my laptop I get the error below, with
```
In [2]: pandas.__version__
Out[2]: '0.20.3'
In [4]: numpy.__version__
Out[4]: '1.16.2'
In [5]: netCDF4.__version__
Out[5]: '1.2.9'
In [15]: xarray.__version__
Out[15]: '0.9.6'
```

```
======================================================================
ERROR: Test reading and writing of storm formats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 158, in decode_cf_datetime
    dates = (pd.to_timedelta(flat_num_dates, delta) + ref_date).values
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/pandas/core/indexes/datetimelike.py", line 660, in __add__
    return self._add_datelike(other)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/pandas/core/indexes/timedeltas.py", line 356, in _add_datelike
    result = checked_add_with_arr(i8, other.value)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/pandas/core/algorithms.py", line 891, in checked_add_with_arr
    raise OverflowError("Overflow in int64 addition")
OverflowError: Overflow in int64 addition

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 393, in __init__
    result = decode_cf_datetime(example_value, units, calendar)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 161, in decode_cf_datetime
    dates = _decode_datetime_with_netcdf4(flat_num_dates, units, calendar)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 103, in _decode_datetime_with_netcdf4
    dates = np.asarray(nc4.num2date(num_dates, units, calendar))
  File "netCDF4/_netCDF4.pyx", line 5555, in netCDF4._netCDF4.num2date
  File "netcdftime/_netcdftime.pyx", line 880, in netcdftime._netcdftime.utime.num2date
  File "netcdftime/_netcdftime.pyx", line 389, in netcdftime._netcdftime.DateFromJulianDay
ValueError: year 5874656 is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/rjl/git/clawpack/geoclaw/tests/test_storm.py", line 159, in test_storm_IO
    raise e
  File "/Users/rjl/git/clawpack/geoclaw/tests/test_storm.py", line 130, in test_storm_IO
    test_storm = storm.Storm(input_path, file_format=file_format, **kwargs)
  File "/Users/rjl/git/clawpack/clawpack/geoclaw/surge/storm.py", line 195, in __init__
    self.read(path, file_format=file_format, **kwargs)
  File "/Users/rjl/git/clawpack/clawpack/geoclaw/surge/storm.py", line 251, in read
    getattr(self, 'read_%s' % file_format.lower())(path, **kwargs)
  File "/Users/rjl/git/clawpack/clawpack/geoclaw/surge/storm.py", line 516, in read_ibtracs
    with xr.open_dataset(path) as ds:
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/backends/api.py", line 301, in open_dataset
    return maybe_decode_store(store, lock)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/backends/api.py", line 225, in maybe_decode_store
    drop_variables=drop_variables)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 955, in decode_cf
    decode_coords, drop_variables=drop_variables)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 888, in decode_cf_variables
    decode_times=decode_times)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 825, in decode_cf_variable
    data = DecodedCFDatetimeArray(data, units, calendar)
  File "/Users/rjl/miniconda/envs/geo/lib/python3.6/site-packages/xarray/conventions.py", line 402, in __init__
    raise ValueError(msg)
ValueError: unable to decode time units 'days since 1858-11-17 00:00:00' with calendar 'standard'. Try opening your dataset with decode_times=False.

----------------------------------------------------------------------
Ran 29 tests in 74.976s

FAILED (SKIP=1, errors=1)
```

**Comment by mandli** [comment]
Fixed in #370.
