### ISSUE TITLE
potential issue with syntax in GDAL

### ISSUE THREAD

**Issue by smmorey** [clawpack/geoclaw#408]
I'm currently trying to get some GeoClaw results up and running in Google Earth but am running into what I think are some Python 3.7 incompatibilities. When following the documented workflow (here: http://www.clawpack.org/googleearth_plotting.html), I get this error when testing the instalation of GDAL: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/smmorey/anaconda3/share/gdal/gdal_test.py", line 79, in <module>
    docfile.write(etree.tostring(etree.ElementTree(doc),pretty_print=True))
TypeError: write() argument must be str, not bytes
```
This is referencing the gdal_test.py file I downloaded from the above link. I'm pretty sure this is just a change in syntax python updates, but I'm can't figure out how to update this line appropriately.

This doesn't seem to be the biggest issue, as GDAL seems optional, but I thought I'd bring it up anyway.

**Comment by mandli** [comment]
I have seen this come up in other contexts as well, mostly plotting though.  I think it may actually be a change in `matplotlib` though.  Definitely deserves some attention to what is really going on though.  @ donnacalhoun have you run into this yet?

**Comment by donnaaboise** [comment]
Thanks for catching this.   I am updating the test now, but here is a quick fix you can try : 

Change line 79 to add a “decode()” statement. 

	docfile.write(etree.tostring(etree.ElementTree(doc),pretty_print=True).decode())

Can you let me know whether this works or not? 

Thanks, 

Donna

-----------------------------------
Donna Calhoun
Associate Professor
Department of Mathematics, Mathematics Bldg 241A
Boise State University
1910 University Drive
Boise, ID 83725-1555
(208) 426-3386
http://math.boisestate.edu/~calhoun
-----------------------------------

**Comment by smmorey** [comment]
That worked! Thanks, Donna!

**Comment by donnaaboise** [comment]
Thanks for confirming that. 

You probably had to make other changes to the gdal_test.py example (e.g. the print statement). 

Did you have to make any more substantial changes? 

Thanks again, 

Donna

-----------------------------------
Donna Calhoun
Associate Professor
Department of Mathematics, Mathematics Bldg 241A
Boise State University
1910 University Drive
Boise, ID 83725-1555
(208) 426-3386
http://math.boisestate.edu/~calhoun
-----------------------------------

**Comment by mandli** [comment]
Does this work across versions of Python?

**Comment by donnaaboise** [comment]
Not sure about that, but I know that it was required when converting to Python 3.x

I can try it in Python 2.x, once I get my version of gdal working. 

-----------------------------------
Donna Calhoun
Associate Professor
Department of Mathematics, Mathematics Bldg 241A
Boise State University
1910 University Drive
Boise, ID 83725-1555
(208) 426-3386
http://math.boisestate.edu/~calhoun
-----------------------------------

**Comment by smmorey** [comment]
I had to change the print statements in gdal_test.py and also a couple of print statements in factory.py within pykml, but nothing major besides that.

**Comment by smmorey** [comment]
It ran fine for me without the updated line in Python 2.7.

**Comment by donnaaboise** [comment]
Right - the updated line wasn’t needed in Python 2.7.   But does the updated line work in 2.7?  (I think it should;  the .decode() statement was probably just assumed in 2.7)


-----------------------------------
Donna Calhoun
Associate Professor
Department of Mathematics, Mathematics Bldg 241A
Boise State University
1910 University Drive
Boise, ID 83725-1555
(208) 426-3386
http://math.boisestate.edu/~calhoun
-----------------------------------

**Comment by mandli** [comment]
I am not sure but I think your assumption is probably correct.  At the very least we should test this and if there is a difference then fence it off with a check on the version of Python if need be.
