### ISSUE TITLE
installing clawpack ubuntu

### ISSUE THREAD

**Issue by jeeckman** [clawpack/geoclaw#517]
Hello,
I have a problem installing Clawpack on my linux.
I have followed the process given here: https://www.clawpack.org/installing.html
(i've tried with pip, git or .tar solution, all give the same trouble)
I fixed the correct CLAW and FC variables.

Testing pyclaw with nosetest returns me OK so it's good. But when I when to run the first test euler_2d, i've a python error in setrun.py:
File "setrun.py", line 28, in setrun
    from clawpack.clawutil import data 

Same, in classic/tests, nosetests -sv returns me OK.
In classic/examples/acoustics_1d_example1,
make. exe correctly creates xclaw, but make .data  returns the python error:
  File "setrun.py", line 28, in setrun
    from clawpack.clawutil import data 

Any idea of the problem?
Thank you,
J.

**Comment by mandli** [comment]
Hi @jeeckman.  Can you import `clawpack.clawutil.data` from a Python command line?

**Comment by jeeckman** [comment]
from a Python prompt:

>>> import clawpack.clawutil.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named clawpack.clawutil.data

**Comment by mandli** [comment]
If Python cannot see the modules from the Python prompt this usually implies that the installation of clawpack was installed into an alternate version of Python.  Do you know if you have multiple versions of Python on your machine?  Anaconda for instance may cause this.
