### ISSUE TITLE
AttributeError: Unrecognized attribute: max1d in chile2010 

### ISSUE THREAD

**Issue by Thomas-Ulrich** [clawpack/geoclaw#535]
Hi,
It might be that the chile2010 example is not anymore compatible with the latest clawpack version:
I mean, I ve been doing a fresh install following https://github.com/clawpack/clawpack#creating-a-read-only-development-version-of-clawpack and compiled geoclaw using the Makefile of the chile2010 (adding only ```FFLAGS =-DNETCDF -I/usr/include/ -lnetcdff -O2 -fopenmp```) example and got the following error when running ```make .output```:

```
make data -f  Makefile /home/ulrich/clawpack//geoclaw/src/2d/shallow/Makefile.geoclaw /home/ulrich/clawpack//clawutil/src/Makefile.common
make[1]: Entering directory '/home/ulrich/clawpack/geoclaw/examples/tsunami/chile2010b'
Makefile:66: warning: overriding recipe for target 'all'
/home/ulrich/clawpack//clawutil/src/Makefile.common:294: warning: ignoring old recipe for target 'all'
rm -f .data
python setrun.py         geoclaw                  
*** Unrecognized attribute:  max1d
*** Perhaps a typo?
*** Add new attributes using add_attribute method
Traceback (most recent call last):
  File "setrun.py", line 430, in <module>
    rundata = setrun(*sys.argv[1:])
  File "setrun.py", line 283, in setrun
    amrdata.max1d = 60
  File "/home/ulrich/.local/lib/python3.8/site-packages/clawpack/clawutil/data.py", line 196, in __setattr__
    raise AttributeError("Unrecognized attribute: %s" % name)
AttributeError: Unrecognized attribute: max1d
make[1]: *** [/home/ulrich/clawpack//clawutil/src/Makefile.common:213: data] Error 1
make[1]: Leaving directory '/home/ulrich/clawpack/geoclaw/examples/tsunami/chile2010b'
make: *** [/home/ulrich/clawpack//clawutil/src/Makefile.common:209: .data] Error 2
```
If I comment the ```amrdata.max1d = 60```, I then get:
```
(base) ulrich@ulrich-ThinkPad-T490s:~/clawpack/geoclaw/examples/tsunami/chile2010b$ make .output
Makefile:66: warning: overriding recipe for target 'all'
/home/ulrich/clawpack//clawutil/src/Makefile.common:294: warning: ignoring old recipe for target 'all'
make data -f  Makefile /home/ulrich/clawpack//geoclaw/src/2d/shallow/Makefile.geoclaw /home/ulrich/clawpack//clawutil/src/Makefile.common
make[1]: Entering directory '/home/ulrich/clawpack/geoclaw/examples/tsunami/chile2010b'
Makefile:66: warning: overriding recipe for target 'all'
/home/ulrich/clawpack//clawutil/src/Makefile.common:294: warning: ignoring old recipe for target 'all'
rm -f .data
python setrun.py         geoclaw                  
Traceback (most recent call last):
  File "setrun.py", line 431, in <module>
    rundata.write()
  File "/home/ulrich/.local/lib/python3.8/site-packages/clawpack/clawutil/data.py", line 543, in write
    data_object.write(out_file=fpath)
  File "/home/ulrich/.local/lib/python3.8/site-packages/clawpack/geoclaw/data.py", line 177, in write
    self._out_file.write("%3i %3i %3i %20.10e %20.10e \n" % tuple(tfile[:-1]))
TypeError: not enough arguments for format string
make[1]: *** [/home/ulrich/clawpack//clawutil/src/Makefile.common:213: data] Error 1
make[1]: Leaving directory '/home/ulrich/clawpack/geoclaw/examples/tsunami/chile2010b'
make: *** [/home/ulrich/clawpack//clawutil/src/Makefile.common:209: .data] Error 2
```

**Comment by mandli** [comment]
Given the errors you are seeing my guess is that the Python you were using from the old version did not get replaced correctly (this can be tricky depending on how you installed the code originally).  The `max1d` parameter was added for instance about a year ago or a bit more.  What you can try is to use `pip install -U -e .` to get it to replace the installed Python.  If that's not it then I am a bit at a loss.

**Comment by Thomas-Ulrich** [comment]
Ok, that was it, sorry, I guess I clone the repository without installing...

**Comment by mandli** [comment]
No worries, I have done that at least a dozen times on accident.
