### ISSUE TITLE
Error with PETSc options for 2D Boussinesq solver in GeoClaw

### ISSUE THREAD

**Issue by carlosmunozmoncayo** [clawpack/geoclaw#606]
Hello, 

I am having issues running the example in `geoclaw/examples/bouss/radial_flat`. After setting the environment variables as described in `geoclaw/examples/bouss/setenv.sh`, and running `make .output` in `geoclaw/examples/bouss/radial_flat`, I get the error attached below.  
I think the error is caused by the line `-pc_type mpi` in the PETSc options file `geoclaw/examples/bouss/petscMPIoptions`.
If I don't use that flag, the code runs successfully, but the solution is not the expected radially symmetric one (I guess the linear systems are not solved correctly with the default options):
<img width="458" alt="image" src="https://github.com/clawpack/geoclaw/assets/29715468/6d0fe356-c761-4bae-adc0-7a1462b964d5">
I am using PETSc version 3.21, and it's passing all the installation tests.

Any ideas on what is causing this error? 
Thank you very much for your help!

`[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Null argument, when expecting valid pointer
[0]PETSC ERROR: Null Pointer: Parameter 'haystack' # 1
[0]PETSC ERROR: WARNING! There are unused option(s) set! Could be the program crashed before usage or a spelling mistake, etc!
[0]PETSC ERROR:   Option left: name:-ksp_type value: preonly source: file
[0]PETSC ERROR:   Option left: name:-mpi_ksp_max_it value: 200 source: file
[1]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[1]PETSC ERROR: Null argument, when expecting valid pointer
[1]PETSC ERROR: [0]PETSC ERROR:   Option left: name:-mpi_ksp_reuse_preconditioner (no value) source: file
[0]PETSC ERROR:   Option left: name:-mpi_ksp_rtol value: 1.e-9 source: file
[0]PETSC ERROR: Null Pointer: Parameter 'haystack' # 1
[1]PETSC ERROR: WARNING! There are unused option(s) set! Could be the program crashed before usage or a spelling mistake, etc!
[1]PETSC ERROR:   Option left: name:-mpi_ksp_type value: gmres source: file
[0]PETSC ERROR:   Option left: name:-mpi_linear_solver_server_view (no value) source: file
[0]PETSC ERROR:   Option left: name:-mpi_pc_gamg_sym_graph value: true source: file
[0]PETSC ERROR:   Option left: name:-ksp_type value: preonly source: file
[1]PETSC ERROR:   Option left: name:-mpi_ksp_max_it value: 200 source: file
[1]PETSC ERROR:   Option left: name:-mpi_ksp_reuse_preconditioner (no value) source: file
[1]PETSC ERROR:   Option left: name:-mpi_ksp_rtol value: 1.e-9 source: file
  Option left: name:-mpi_pc_gamg_symmetrize_graph value: true source: file
[0]PETSC ERROR:   Option left: name:-mpi_pc_type value: gamg source: file
[0]PETSC ERROR:   Option left: name:-pc_mpi_minimum_count_per_rank value: 5000 source: file
[1]PETSC ERROR:   Option left: name:-mpi_ksp_type value: gmres source: file
[1]PETSC ERROR:   Option left: name:-mpi_linear_solver_server_view (no value) source: file
[1]PETSC ERROR: [0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.21.0, unknown 
  Option left: name:-mpi_pc_gamg_sym_graph value: true source: file
[1]PETSC ERROR:   Option left: name:-mpi_pc_gamg_symmetrize_graph value: true source: file
[1]PETSC ERROR: [0]PETSC ERROR: /Users/carlos/clawpack/geoclaw/examples/bouss/radial_flat/xgeoclaw on a arch-darwin-c-debug named laptop.local by carlos Mon May  6 20:30:29 2024
[0]PETSC ERROR: Configure options --download-mpich
  Option left: name:-mpi_pc_type value: gamg source: file
[1]PETSC ERROR:   Option left: name:-pc_mpi_minimum_count_per_rank value: 5000 source: file
[1]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: #1 PetscStrstr() at /Users/carlos/SciSoftware/petsc/include/petscstring.h:402
[0]PETSC ERROR: [1]PETSC ERROR: Petsc Release Version 3.21.0, unknown 
[1]PETSC ERROR: /Users/carlos/clawpack/geoclaw/examples/bouss/radial_flat/xgeoclaw on a arch-darwin-c-debug named laptop.local by carlos Mon May  6 20:30:29 2024
#2 PCCreate_MPI() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/impls/mpi/pcmpi.c:763
[0]PETSC ERROR: #3 PCSetType() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/interface/pcset.c:75
[0]PETSC ERROR: [1]PETSC ERROR: Configure options --download-mpich
[1]PETSC ERROR: #1 PetscStrstr() at /Users/carlos/SciSoftware/petsc/include/petscstring.h:402
#4 PCSetFromOptions() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/interface/pcset.c:146
[0]PETSC ERROR: #5 KSPSetFromOptions() at /Users/carlos/SciSoftware/petsc/src/ksp/ksp/interface/itcl.c:356
[0]PETSC ERROR: [1]PETSC ERROR: #2 PCCreate_MPI() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/impls/mpi/pcmpi.c:763
[1]PETSC ERROR: #6 PCMPISetMat() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/impls/mpi/pcmpi.c:273
[0]PETSC ERROR: #7 PCSetUp_MPI() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/impls/mpi/pcmpi.c:663
#3 PCSetType() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/interface/pcset.c:75
[1]PETSC ERROR: #4 PCSetFromOptions() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/interface/pcset.c:146
[1]PETSC ERROR: [0]PETSC ERROR: #8 PCSetUp() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/interface/precon.c:1079
[0]PETSC ERROR: #9 KSPSetUp() at /Users/carlos/SciSoftware/petsc/src/ksp/ksp/interface/itfunc.c:415
[0]PETSC ERROR: #10 KSPSolve_Private() at /Users/carlos/SciSoftware/petsc/src/ksp/ksp/interface/itfunc.c:831
#5 KSPSetFromOptions() at /Users/carlos/SciSoftware/petsc/src/ksp/ksp/interface/itcl.c:356
[1]PETSC ERROR: #6 PCMPISetMat() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/impls/mpi/pcmpi.c:273
[1]PETSC ERROR: #7 PCMPIServerBegin() at /Users/carlos/SciSoftware/petsc/src/ksp/pc/impls/mpi/pcmpi.c:465
[1]PETSC ERROR: #8 PetscInitialize_Common() at /Users/carlos/SciSoftware/petsc/src/sys/objects/pinit.c:1149
[0]PETSC ERROR: #11 KSPSolve() at /Users/carlos/SciSoftware/petsc/src/ksp/ksp/interface/itfunc.c:1078
[1]PETSC ERROR: PetscInitialize:PetscInitialize_Common
[1]PETSC ERROR: #9 /Users/carlos/SciSoftware/petsc/src/sys/f90-mod/petscsysmod.F90:387
[1]PETSC ERROR: #10 /Users/carlos/clawpack/geoclaw/src/2d/bouss/amr2.f90:165
application called MPI_Abort(MPI_COMM_SELF, 85) - process 0
Traceback (most recent call last):
  File "/Users/carlos/clawpack/clawutil/src/python/clawutil/runclaw.py", line 242, in runclaw
    proc = subprocess.check_call(cmd_split,
  File "/Users/carlos/.pyenv/versions/3.8.9/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/carlos/SciSoftware/petsc/arch-darwin-c-debug/bin/mpiexec', '-n', '6', '/Users/carlos/clawpack/geoclaw/examples/bouss/radial_flat/xgeoclaw']' returned non-zero exit status 85.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlos/clawpack/clawutil/src/python/clawutil/runclaw.py", line 341, in <module>
    runclaw(*args)
  File "/Users/carlos/clawpack/clawutil/src/python/clawutil/runclaw.py", line 249, in runclaw
    raise ClawExeError(exe_error_str, cpe.returncode, cpe.cmd,
__main__.ClawExeError: 

*** FORTRAN EXE FAILED ***

make[1]: *** [output] Error 1
make: *** [.output] Error 2
`

**Comment by renzhy** [comment]
Hi, have you solve this problem?

**Comment by carlosmunozmoncayo** [comment]
@mjberger yes, the default options are working for me after checking out commit 162d2c2fef81b083a2f638272d91dbb534012011 and using PETSc 3.22. Thank you!
